# prometheus-operator.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: core
spec:
  chart:
    repository: https://github.com/coreos/
    name: prometheus-operator
    version: 8.15.10
  values:
    apiService:
      create: true